apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-conf
data:
  index.php: |
    <?php phpinfo(); ?>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  labels:
    app: apache
spec:
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: php:apache
        ports:
          - containerPort: 80
        volumeMounts:
          - name: apache-volume
            mountPath: /var/www/html/index.php
            subPath: index.php
        
      volumes:
      - name: apache-volume
        configMap:
          name: apache-conf
          items:
            - key: index.php
              path: index.php

---
apiVersion: v1
kind: Service
metadata:
  name: apache
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30009
  selector:
    app: apache
