apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |
    server {
    	server_name kubnginxname.ddns.net;
    	listen 80;
      
    	location / {
          root /etc/nginx/example.com;
    	    index  example.html;
    	}
    	location /anotherport {
     	    proxy_pass http://localhost:8888/;
    	}
    	location /music {
    	}
    	location ~ \.php$ {
          proxy_pass http://kubnginxname.ddns.net:30009;
          proxy_set_header X-Real-IP  $remote_addr;
          proxy_set_header X-Forwarded-For $remote_addr;
          proxy_set_header Host $host;
    	}	
    	location ~ /\. {
        	deny all;
    	}
    	location /secondserver {
        	return https://playsdev.com;
    	}
    	location /redblue {
    	        proxy_pass http://redblue/;
    	        proxy_redirect off;
    	        proxy_http_version 1.1;
    	        proxy_set_header Upgrade $http_upgrade;
    	        proxy_set_header Connection "upgrade";
    	}
    	location ~* \.(png) {
            root /etc/nginx/example.com;
    	    include /etc/nginx/mime.types;
    	}
    	location ~* \.(jpg|jpeg) {
                root /etc/nginx/example.com;
        	include /etc/nginx/mime.types;
        	image_filter rotate 180;
    	}
    	error_page   500 502 503 504  /50x.html;
    	location = /50x.html {
        	root   /usr/share/nginx/html;
    	}
    	error_page 400 402 403 404 /404.html;
    	location = /404.html {
        	root /usr/share/nginx/html;
    	}
    	location /500 {
            return 500;
    	}
        location /400 {
            return 400;
    	}
    }
    upstream redblue{
    	server localhost:9999;
        server localhost:9998;
    }

    server {
    	listen 8888;
    	location / {
    	    root /etc/nginx/example.com;
    	    index example8888.html;
    	}
    }

    server {
    	listen 9999;
    	location / {
    	    root /etc/nginx/example.com;
    	    index red.html;
    	}
    }
    server {
    	listen 9998;
    	location / {
    	    root /etc/nginx/example.com;
    	    index blue.html;
    	}
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: dememedp/final:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
            readOnly: true
              #- name: apache
              #image: php:apache
              #ports:
              #- containerPort: 8080
              #name: apache
              #volumeMounts:
          - name: apache-conf
            mountPath: /etc/nginx/example.com
            #subPath: index.php
            
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        startupProbe:
          tcpSocket:
            port: 80
          failureThreshold: 30
          periodSeconds: 10
        
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
      - name: apache-conf
        configMap:
        name: apache-conf
            #items:
            #- key: index.php
            #path: index.php

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30008
  selector:
    app: nginx
